# Generated by Django 5.2.7 on 2025-10-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="blog_image/default_error.png", upload_to="blog_image/%Y/%m/%d/"
            ),
        ),
    ]
